services:
  - type: web
    name: clearcast-server
    runtime: python
    repo: https://github.com/BarishHalder/ClearCast-server
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    autoDeploy: true
